"""person-org-name

Revision ID: 60af550739a9
Revises: 75f308ecf6f7
Create Date: 2023-01-03 18:26:21.536101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60af550739a9'
down_revision = '75f308ecf6f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('organization_name', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'organization_name')
    # ### end Alembic commands ###
