"""unit-cat-num

Revision ID: 70f218fa236f
Revises: 153540452e14
Create Date: 2022-12-13 16:14:58.622056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70f218fa236f'
down_revision = '153540452e14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unit', sa.Column('catalog_number', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('unit', 'catalog_number')
    # ### end Alembic commands ###
